spring:
  main:
    webApplicationType: NONE

sattrackclient:

  # SatTrackAPI base URL
  satTrackApiUrl: https://sattrackapi.ultima.hr:8443/api/v1

  # station details
  station:
    name: "Pregrada/Kunagora"
    latitude: 46.1685
    longitude: 15.7484
    altitude: 380

  # satellites we're tracking
  satelliteData:
    - id: 25338
      name: "NOAA15"
      radioFrequency: 137.5
      minElevation: 25.0
      stepSize: 0
      rotatorEnabled: false
      satRiseShellCmd: ""
      satSetShellCmd: ""
    - id: 28654
      name: "NOAA18"
      radioFrequency: 137.19125
      minElevation: 25.0
      stepSize: 0
      rotatorEnabled: false
      satRiseShellCmd: ""
      satSetShellCmd: ""
    - id: 33591
      name: "NOAA19"
      radioFrequency: 137.1
      minElevation: 25.0
      stepSize: 0
      rotatorEnabled: false
      satRiseShellCmd: ""
      satSetShellCmd: ""
