spring:
  main:
    # REST client dependencies are included by Spring Boot, which also provide a web server.
    # Here we disable starting an embedded web server.
    webApplicationType: NONE

sancho:

  # enable/disable automatic scheduling
  # disable scheduler for unit testing
  schedulerAutoStartDisabled: false

  # how long do we wait in case of error
  # while scheduling next event, in seconds
  schedulerErrorWait: 180

  # SatTrackAPI base URL
  satTrackApiUrl: https://sattrackapi.ultima.hr:8443/api/v1

  # station details
  station:
    name: "Pregrada/Kunagora"
    latitude: 46.1685
    longitude: 15.7484
    altitude: 380

  # rotctld backend configuration
  rotator:
    rotctldHost: 127.0.0.1
    rotctldPort: 14533
    stepSize: 0.25 # how often do we update the rotator position, in seconds; 0.25 is a sensible default

  # satellites we're tracking

  # You can use the following placeholders in shell cmd templates:
  # ${tle} - string (note that newline is passed as literal '\n')
  # ${satId} - string
  # ${satName} - string
  # ${radioFrequency} - double [MHz]
  # ${predictTime} - Unix epoch
  # ${rise} - Unix epoch
  # ${set} - Unix epoch
  # ${duration} - double [sec]
  satelliteData:
    - id: 25338
      name: "NOAA15"
      radioFrequency: 137.62
      minElevation: 20.0
      trackingElevationThreshold: 35.0
      stepSize: 0
      rotatorEnabled: false
      satRiseShellCmdTemplate: "/opt/ultima/apt-receive/capture.sh '${tle}' ${satId} ${satName} ${radioFrequency} ${predictTime} ${rise} ${set} ${duration}"
      satSetShellCmdTemplate: ""
    - id: 28654
      name: "NOAA18"
      radioFrequency: 137.9125
      minElevation: 20.0
      trackingElevationThreshold: 35.0
      stepSize: 0
      rotatorEnabled: false
      satRiseShellCmdTemplate: "/opt/ultima/apt-receive/capture.sh '${tle}' ${satId} ${satName} ${radioFrequency} ${predictTime} ${rise} ${set} ${duration}"
      satSetShellCmdTemplate: ""
