spring:
  main:
    webApplicationType: NONE

sattrackclient:

  # SatTrackAPI base URL
  satTrackApiUrl: https://sattrackapi.ultima.hr:8443/api/v1

  # station details
  station:
    name: "Pregrada/Kunagora"
    latitude: 46.1685
    longitude: 15.7484
    altitude: 380

  rotatorConfig:
    rotctldHost: 127.0.0.1
    rotctldPort: 14533
    waitAfterParkingCommand: 30 # seconds
    stepSize: 0.25 # seconds

  # satellites we're tracking

  # You can use the following placeholders in shell cmd templates:
  # ${satId} - string
  # ${satName} - string
  # ${radioFrequency} - double [MHz]
  # ${predictTime} - Unix epoch
  # ${rise} - Unix epoch
  # ${set} - Unix epoch
  # ${duration} - double [sec]
  satelliteData:
    - id: 25338
      name: "NOAA15"
      radioFrequency: 137.62
      minElevation: 30.0
      stepSize: 1
      rotatorEnabled: true
      satRiseShellCmdTemplate: ""
      satSetShellCmdTemplate: ""
    - id: 28654
      name: "NOAA18"
      radioFrequency: 137.9125
      minElevation: 30.0
      stepSize: 1
      rotatorEnabled: true
      satRiseShellCmdTemplate: ""
      satSetShellCmdTemplate: ""
    - id: 33591
      name: "NOAA19"
      radioFrequency: 137.1
      minElevation: 30.0
      stepSize: 1
      rotatorEnabled: true
      satRiseShellCmdTemplate: ""
      satSetShellCmdTemplate: ""
