#!/usr/bin/env ansible-playbook
---
- name: Sancho - deploy as a systemd service
  hosts: rpisdr
  become: True
  become_user: root
  become_method: sudo

  vars_files:
    - vars/rpisdr.yml

  roles:
    - { role: deploy-app }
