#!/usr/bin/env ansible-playbook
---
- name: SatTrackClient - production deploy
  hosts: production
  become: True
  become_user: root
  become_method: sudo

  vars_files:
    - vars/production.yml

  roles:
    - { role: deploy-app }
